### ISSUE TITLE
Calibrate screen

### ISSUE THREAD

**Issue by TheJackiMonster** [TheJackiMonster/HuionGT191LinuxDriver#3]
There is still a little problem with the projection of the pen to its cursor-position. There is a changing offset between cursor and pen depending to the pen's position on the screen. This effect needs a calibration hopefully by just four points in the corners of the screen.

But this means it needs a seperate program for this calibration, a configuration for the driver etc.

I could use this problem to add functionality to a configuration like 'binding buttons of the pen' and others...

**Comment by TheJackiMonster** [comment]
Calibration is now possible in a manual (the hard) way, if you have xinput installed and you know how to use it. My tests so far with OpenCV's homography to calibrate the screen did mess up and seems to be the wrong way... maybe it's just a very small rotation which can fix the cursor's position.

**Comment by TheJackiMonster** [comment]
I will try to setup the possibility to calibrate the pen's coordinates via a neuronal network which could learn from every calibration the user executes dynamicly. I will use my own short library written in C in the beginning (maybe the delay isn't perfect, but first it's more important that it works ^^).

**Comment by insomniacUNDERSCORElemon** [comment]
Forgive me if I'm wrong, but if this is anything like johnp789's hack of Benethor's userspace driver, it's not really a 'calibration' issue so much as it is simply a completely unconfigured draw area.

Particularly the effect I'm talking about is that the closer to the edges you get, the more offset it is. That's because the digitizer is larger than the display (likely so drawing to the edge of the screen works, maybe for a place dedicated for secondary buttons without drawing). The fix to this is to properly designate the drawing area and set up some sort of clamp at the screen's edge (and maybe ignore the pen action after a certain point).

<details>
<summary>If this is the case...</summary>
The clamp I'd recommend would be to have differing logic depending on where the pen started. Started in this case means where the pen was placed in this period of drawing.
<hr></hr>
If it started in the 'real' drawing area, the pen would stop drawing at the edge of the screen (so a drawn line properly ends) but continue to send clamped mouse data. The pen would continue drawing if it re-enters the 'real' drawing area... although since drawing was terminated this will count as a new line (the line won't "jump" like some logical errors happen when mouse focus is lost).
<hr></hr>
If started in one of the 'margins', it would still be clamped but would allow drawing. This would cause the edges of the screen to act as a straight-edge. If drawn in only the margins, a rectangle could be drawn, if switched from margin-to screen-to margin it'd continue clamping at the edge (for example you could use this to make a right triangle).
<hr></hr>
<hr></hr>
Yeah, on paper this sounds silly but combined with your art program's panning, it could prove more useful than using in-editor tools or using physical stencils/rulers with your drawing monitor to get the desired effect.
<hr></hr>
Maybe this could be used for more customization. Particularly more hotkeys (which the GT-191 is low on compared to other drawing monitors, like the GT-221 or GAOMON PD1560), for instance I might set my 2 pen hotkeys to eraser+spaceclick(to pan) when pressed in the drawing area and undo+mirror view when pressed in the margin. 
<hr></hr>
Unfortunately as fun a simulated mouse-clicks from within the margins would be (assuming the action is held in the main drawing area until released, like using the margin to start drawing a line via a line tool), this wouldn't work very well in reality because the mouse click wouldn't land on the canvas unless you were drawing in fullscreen with no GUI.
</details>

**Comment by TheJackiMonster** [comment]
Actually fixing this problem with a margin was my first idea too, but after multiple tests I came to the result, that the margin had to be unequal at the borders or something, so I tested a homography for projection to fix it. This didn't work either and after a closer look, it seemed the grid for detection of the pen's position in the screen is more unaccurate at borders than in the center, but even the center isn't correct. It's not a simple issue in my opinion, but in every case a solution with a neuronal network should work and if the results explain the problem, I can still find an easier solution.

Maybe it's even different on every individual device, but I get a different offset from the pen's tip to the cursor on the screen. It's relative small but I can't deny that it's there and I would like to get an accurate position for drawing.

**Comment by insomniacUNDERSCORElemon** [comment]
Hmm. Are you sure the tiny offset isn't normal parallax (from the glass, which could be caused by differences/inaccuracy in manufacturing, or standard thickness), or by something odd (electromagnetic interference, difference in pen construction, pen nib wear, pen battery charge, screen/screen protector wear, temperature of the electronics etc)?

Also could you get the _majority_ of offset gone with the margin fix? Because with the userspace driver I was using it was pretty major (about 1in/2mm near the edges IIRC, maybe a bit more, probably around the size of the margins themselves).

I know even a slight parallax bothers some people, but even fixing the margins would be good enough for many (forgive me if you've implemented it already). Adding the margin features as I described in the spoiler (especially alternate button bindings) would also be a big usability plus.

**Comment by TheJackiMonster** [comment]
I've done the calibration now and after multiple rounds learning, the network shows, that there isn't a problem of offset/margin by the numbers. Also what I said is the offset is different at different positions. Try to look at it in every corner of the screen closely. It should be different and in my case, when I draw a line from one corner to its neighbour, the offset isn't a straight line.. more like a curve.

I hope, my implementation can fix this problem, but anyway.. even if it's a physical problem, it's not like the values would vary or something, so there has to be a algorithmic solution for it.

But since the calibration-functionality is done now, I can look again for a margin or something similar to fix the problem you said, even if my previous tests contradict such a thing.. it's less work than what I implemented now. ^_^
