### ISSUE TITLE
Long-running driver generates a large number of libusb errors

### ISSUE THREAD

**Issue by scurest** [TheJackiMonster/HuionGT191LinuxDriver#9]
I have a problem where the driver generates a large number of errors. I can't tell under what exact conditions it occurs but it seems to occur only after `Driver` runs for a long time. Restarting the driver fixes it and it seems to take several days to occur again. The symptoms are

* the `Driver` process and `journalctl` spike to 100% CPU usage
* journalctl records a huge number of errors of the form

        process 16339 (Driver) did not claim interface 0 before use

* after setting the libusb log level to `LIBUSB_LOG_LEVEL_WARNING`, the `Driver` continually spits out 

        libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=16

I'll try to add checks to figure out what call precisely is causing the error, but it's slow going since it takes so long to reproduce.

**Comment by TheJackiMonster** [comment]
Good to know that. I didn't test it for such a long time yet. The errors do probably occure because the system deactivates the usb connection or removes it completely for a break. I can try to setup a workaround so that the driver will check for such cases and resets completely automaticly. This just also fix another problem I already encountered. ^^

**Comment by TheJackiMonster** [comment]
As long as the device is still connected via usb the driver should reset its connection automaticly now if it gets any problems.

So if you still get any errors or problems over long time, please report them again. ^^
